// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEz1OvFQrmWvbNa3xlw99FhjZlnSPpccw',
    appId: '1:212600632249:android:d9be2447ee09e6bef67c68',
    messagingSenderId: '212600632249',
    projectId: 'disastermanagementapp-d9ee3',
    storageBucket: 'disastermanagementapp-d9ee3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyUSHVMgRZen5sjHGLXBkVzbqEe06tiE',
    appId: '1:212600632249:web:bb23b38fc7ef8826f67c68',
    messagingSenderId: '212600632249',
    projectId: 'disastermanagementapp-d9ee3',
    authDomain: 'disastermanagementapp-d9ee3.firebaseapp.com',
    storageBucket: 'disastermanagementapp-d9ee3.firebasestorage.app',
    measurementId: 'G-MNPQ77SXJE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8GkunhJvS2D-Gj-OPSkpaB7jD63HFhHg',
    appId: '1:212600632249:ios:b74125830d8c1699f67c68',
    messagingSenderId: '212600632249',
    projectId: 'disastermanagementapp-d9ee3',
    storageBucket: 'disastermanagementapp-d9ee3.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8GkunhJvS2D-Gj-OPSkpaB7jD63HFhHg',
    appId: '1:212600632249:ios:b74125830d8c1699f67c68',
    messagingSenderId: '212600632249',
    projectId: 'disastermanagementapp-d9ee3',
    storageBucket: 'disastermanagementapp-d9ee3.firebasestorage.app',
    iosBundleId: 'com.example.disasterManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlyUSHVMgRZen5sjHGLXBkVzbqEe06tiE',
    appId: '1:212600632249:web:6821770fd6212413f67c68',
    messagingSenderId: '212600632249',
    projectId: 'disastermanagementapp-d9ee3',
    authDomain: 'disastermanagementapp-d9ee3.firebaseapp.com',
    storageBucket: 'disastermanagementapp-d9ee3.firebasestorage.app',
    measurementId: 'G-Y83ZZTRVCK',
  );

}